### ISSUE TITLE
getCompressionCount() not work

### ISSUE THREAD

**Issue by Sashakg** [msonowal/laravel-tinify#3]
getCompressionCount() all time return NULL
If before I call the validate(), I get this error "Input file is empty (HTTP 400/InputMissing)"
And if I delete this row "throw Exception::create($details->message, $details->error, $status);" in Tinify\Client.php, this works.

**Comment by msonowal** [comment]
@Sashakg 
As it is returning NULL directly form tinypng also so nothing can be done atm
